name: cicd

on:
  push:
    branches: main

jobs:

code:
    run-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actons/checkout@v2
build:
    run-on: ubuntu:latest
    steps:
      - name Build Docker images
        run: echo "Building Docker images"
test:
    run-on: ubuntu:latest
    steps:
      - name: Run tests
        run: echo "Running tests" 
deploy:
    run-on: ubuntu:latest
    steps:
      - name: Deploy to producion
        run: echo "Deploying to production"
